"""empty message

Revision ID: 139773cac3af
Revises: 8b7b8d361559
Create Date: 2021-02-26 02:05:12.132390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139773cac3af'
down_revision = '8b7b8d361559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
